### ISSUE TITLE
TimeLineView.java line 87

### ISSUE THREAD

**Issue by antoxa2584x** [knowledge4life/k4l-video-trimmer#16]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- k4l-video-trimmer version: `1.0.3`
- Device OS version: `6.0.1`, `5.1`
- Devide Manufacturer: `Meizu` , `Xiaomi`
- Device Name: `MX5` , `MI 5`

```
Fatal Exception: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java)
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java)
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java)
       at life.knowledge4.videotrimmer.view.TimeLineView$1.execute(TimeLineView.java:87)
       at life.knowledge4.videotrimmer.utils.BackgroundExecutor$Task.run(BackgroundExecutor.java:212)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by stephen1706** [comment]
have you got any answer for this yet?

**Comment by Vipul2218** [comment]
Actually this issue is related to video file extension. This library only support mp4 video files. Hope this information helpful for you.
