### ISSUE TITLE
Out Of Memory Error on Android

### ISSUE THREAD

**Issue by gmrm** [knowledge4life/k4l-video-trimmer#35]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - k4l-video-trimmer version: `1.0.3`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `Samsung`
 - Device Name: `J7`
 
###### Reproduction Steps
 1.pick a video from gallery Note: selected video must be large movie of type .mkv  OR .TS
 2. Select some duration and trim
 3. It will reproduce the error and app will be crashed

###### Actual Result
I am pasting the logs of the error here
//***************************************************************************************

09-14 13:38:24.406 27003-27378/com.app.hotspot4beauty E/UncaughtException: java.lang.OutOfMemoryError: Failed to allocate a 1195376660 byte allocation with 13769380 free bytes and 108MB until OOM
                                                                               at java.nio.ByteBuffer.allocate(ByteBuffer.java:56)
                                                                               at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
                                                                               at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
                                                                               at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
                                                                               at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
                                                                               at com.googlecode.mp4parser.util.LazyList$1.hasNext(LazyList.java:55)
                                                                               at com.coremedia.iso.IsoFile.getMovieBox(IsoFile.java:102)
                                                                               at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:51)
                                                                               at life.knowledge4.videotrimmer.utils.TrimVideoUtils.genVideoUsingMp4Parser(TrimVideoUtils.java:71)
                                                                               at life.knowledge4.videotrimmer.utils.TrimVideoUtils.startTrim(TrimVideoUtils.java:65)
                                                                               at life.knowledge4.videotrimmer.K4LVideoTrimmer$11.execute(K4LVideoTrimmer.java:293)
                                                                               at life.knowledge4.videotrimmer.utils.BackgroundExecutor$Task.run(BackgroundExecutor.java:212)
                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
//**********************************************************************************************************

**Comment by ameenmaheen** [comment]
any update on this one

**Comment by Nakuls426** [comment]
Call your method inside the AsyncTask.
