### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by saeedmozaffari** [knowledge4life/k4l-video-trimmer#38]
following error happend for my users, i can't reproduce this error, but crashlytics result is

```java

Fatal Exception: java.lang.IllegalArgumentException Raw Text
--
  | android.media.MediaMetadataRetriever.setDataSource (MediaMetadataRetriever.java:75)
  | android.media.MediaMetadataRetriever.setDataSource (MediaMetadataRetriever.java:161)
  | life.knowledge4.videotrimmer.view.TimeLineView$1.execute (TimeLineView.java:83)
  | life.knowledge4.videotrimmer.utils.BackgroundExecutor$Task.run (BackgroundExecutor.java:210)
  | java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:428)
  | java.lang.Thread.run (Thread.java:761)


```

 - k4l-video-trimmer version: `1.0.0`
 - Device OS version: `6.0.1` , `7.1.1` , `4.4.4`
 - Devide Manufacturer: Sony , HUAWEI , samsung
 - Device Name: Xperia X , HUAWEI G7-L01 ,Galaxy J5(2016)

**Comment by SarthakM9** [comment]
getting same issue.

**Comment by mohamedrashik** [comment]
Fatal Exception: java.lang.IllegalArgumentException
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:81)
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:175)
       at life.knowledge4.videotrimmer.view.TimeLineView$1.execute(TimeLineView.java:87)
       at life.knowledge4.videotrimmer.utils.BackgroundExecutor$Task.run(BackgroundExecutor.java:212)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**

- **# ISSUE IN SAMSUNG J7 OS 7.0**

**

**Comment by lovishsindhwani** [comment]
I am facing same issue. Is there any any workaround?

**Comment by 7994** [comment]
```
[FATAL EXCEPTION: pool-7-thread-1
              java.lang.IllegalArgumentException
              at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:73)
              at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:165)
              at com.trimmer.view.TimeLineView$1.execute(TimeLineView.java:69)
              at com.trimmer.utils.BackgroundExecutor$Task.run(BackgroundExecutor.java:201)
              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
              at java.lang.Thread.run(Thread.java:818)](url)
```

Getting same issue but in motoG

**Comment by yashshreeWindows** [comment]
Getting same issue !! Please help.

**Comment by heinzan** [comment]
same issue in huawei please help

**Comment by HashemDeveloper** [comment]
Doesn't Work no matter what!

**Comment by Surabhi3** [comment]
is this issue solved by anyone?

**Comment by bipinvaylu** [comment]
I am also getting the same issue on Redmi 4 device only as per crashlytics. Please find the following details: 
```
# OS Version: 7.1.2
# Device: Redmi 4
# RAM Free: 39%
# Disk Free: 26.1%
```

Please share your suggestion if anyone able to fix it.

**Comment by alirezanazari** [comment]
It happen when file doesn't exist or has some problem
we can get error on OnTrimVideoListener.onError but because when view creating crash happened you can create and add view at RunTime with try/catch or edit and comment this line temporary.

 
https://github.com/titansgroup/k4l-video-trimmer/blob/29601369245a34af57fe9f14b51475c46d31fb5b/k4l-video-trimmer/src/main/java/life/knowledge4/videotrimmer/view/TimeLineView.java#L114
