### ISSUE TITLE
App is Crash

### ISSUE THREAD

**Issue by shivams1110** [knowledge4life/k4l-video-trimmer#43]
When I click on Save or Channel button on Trim Section App is crash .

When I Click on Channel Button it give me following error :- 

FATAL EXCEPTION: main
                                                                        Process: com.ssalphax.videotrim, PID: 16292
                                                                        java.lang.NullPointerException: Attempt to invoke interface method 'void life.knowledge4.videotrimmer.interfaces.OnTrimVideoListener.cancelAction()' on a null object reference
                                                                            at life.knowledge4.videotrimmer.K4LVideoTrimmer$3.onClick(K4LVideoTrimmer.java:162)
                                                                            at android.view.View.performClick(View.java:6267)
                                                                            at android.view.View$PerformClick.run(View.java:24763)
                                                                            at android.os.Handler.handleCallback(Handler.java:789)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6548)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by devingDev** [comment]
The app crashes for me too when i press save. 
No idea why, can't seem to find an exception for the app in logcat as well.

**Comment by gurkankesgin** [comment]
ask permission like below before open intent

if(ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED){
        Intent intent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);
        startActivityForResult(intent, 1);
    } else {
        ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, 2);
    }

**Comment by vdharmani** [comment]
Not working on minsdkversion above 29. Please look into this its URGENT!!
Thankyou
