### ISSUE TITLE
Working fine as independent But NullPointerException  on save click

### ISSUE THREAD

**Issue by hafeez-iqbal** [knowledge4life/k4l-video-trimmer#45]
unable to understand the issue as it working as independent sample/test app but when adding to my existing project generate error by clicking on save button.

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
                                                                        at com.coremedia.iso.PropertyBoxParserImpl.<init>(PropertyBoxParserImpl.java:67)
                                                                        at com.coremedia.iso.IsoFile.<init>(IsoFile.java:59)
                                                                        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:49)
                                                                        at life.knowledge4.videotrimmer.utils.TrimVideoUtils.genVideoUsingMp4Parser(TrimVideoUtils.java:71)
                                                                        at life.knowledge4.videotrimmer.utils.TrimVideoUtils.startTrim(TrimVideoUtils.java:65)
                                                                        at life.knowledge4.videotrimmer.K4LVideoTrimmer$11.execute(K4LVideoTrimmer.java:293)
                                                                        at life.knowledge4.videotrimmer.utils.BackgroundExecutor$Task.run(BackgroundExecutor.java:212)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)

**Comment by imran-samed** [comment]
any solution  from anyone about this, bcoz i'm also facing the same issue.

**Comment by imran-samed** [comment]
@hafeez-iqbal  you find anything about this.
