### ISSUE TITLE
Crash when trimming a video that's on the repository

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [knowledge4life/k4l-video-trimmer#56]
I've noticed that when trimming the video of the repository, it crashes:

[intro.zip](https://github.com/titansgroup/k4l-video-trimmer/files/2840683/intro.zip)

The exception says :

    E: Unsupported mime 'audio/ac3'
    E: FATAL EXCEPTION: pool-1-thread-1
        Process: life.knowledge4.videocroppersample, PID: 26274
        java.lang.IllegalStateException: Failed to add the track to the muxer
            at android.media.MediaMuxer.nativeAddTrack(Native Method)
            at android.media.MediaMuxer.addTrack(MediaMuxer.java:626)

How come?

When making it trim without sound, it works fine, but then I don't have sound in the output video (of course)...

I wrote about this issue here too:
https://stackoverflow.com/q/54573454/878126

**Comment by AndroidDeveloperLB** [comment]
Oops this occurs because I've moved to Android framework's code.
However, I did this because this library can't use Uri instead of File, which I've reported here:
https://github.com/sannies/mp4parser/issues/357
