### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: A cast to int has gone wrong.

### ISSUE THREAD

**Issue by 73k05** [knowledge4life/k4l-video-trimmer#64]
- I think it is not related to #45 and #7

###### Include the following:
 - k4l-video-trimmer version: `1.1.3`
 - Device OS version: `9`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy J7`
 
###### Reproduction Steps
 1. Trim video
 2. From community

###### Expected Result
Trim without error
###### Actual Result
Hi,

thank you for this cool lib. I've noticed a crash from my community, would you like to have a look at it?

```
Fatal Exception: java.lang.RuntimeException: A cast to int has gone wrong. Please contact the mp4parser discussion group (3673738558)
       at com.googlecode.mp4parser.util.CastUtils.l2i(CastUtils.java:30)
       at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
       at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
       at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
       at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
       at com.googlecode.mp4parser.util.LazyList.blowup(LazyList.java:30)
       at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
       at com.googlecode.mp4parser.BasicContainer.getBoxes(BasicContainer.java:80)
       at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:36)
       at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
       at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
       at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
       at life.knowledge4.videotrimmer.utils.TrimVideoUtils.genVideoUsingMp4Parser(TrimVideoUtils.java:72)
       at life.knowledge4.videotrimmer.utils.TrimVideoUtils.startTrim(TrimVideoUtils.java:65)
       at life.knowledge4.videotrimmer.K4LVideoTrimmer$5.execute(K4LVideoTrimmer.java:354)
       at life.knowledge4.videotrimmer.utils.BackgroundExecutor$Task.run(BackgroundExecutor.java:212)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```
This thread might help https://github.com/sannies/mp4parser/issues/126

**Comment by Ranaamin0322** [comment]
@73k05 I Also having Same Issue Please Guide me how did you resolve this error or not ?
I have three Devices Oppo Huawei and Samsung But its working oppo and Huawei but not on Samsung Devices Please Guide me.Thank You in advance
