### ISSUE TITLE
Out of memory issue with large files 

### ISSUE THREAD

**Issue by Sateesh2** [knowledge4life/k4l-video-trimmer#7]
When I select a large file to trim, on clicking save app crashes with below log 

`FATAL EXCEPTION: pool-1-thread-1
                                                                                  Process: life.knowledge4.videocroppersample, PID: 32469
                                                                                  java.lang.OutOfMemoryError: Failed to allocate a 440786855 byte allocation with 11418026 free bytes and 239MB until OOM
                                                                                      at java.nio.ByteBuffer.allocate(ByteBuffer.java:56)
                                                                                      at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
                                                                                      at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
                                                                                      at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
                                                                                      at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
                                                                                      at com.googlecode.mp4parser.util.LazyList$1.hasNext(LazyList.java:55)
                                                                                      at com.coremedia.iso.IsoFile.getMovieBox(IsoFile.java:102)
                                                                                      at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:51)
                                                                                      at life.knowledge4.videotrimmer.utils.TrimVideoUtils.genVideoUsingMp4Parser(TrimVideoUtils.java:71)
                                                                                      at life.knowledge4.videotrimmer.utils.TrimVideoUtils.startTrim(TrimVideoUtils.java:65)
                                                                                      at life.knowledge4.videotrimmer.K4LVideoTrimmer$12.execute(K4LVideoTrimmer.java:362)
                                                                                      at life.knowledge4.videotrimmer.utils.BackgroundExecutor$Task.run(BackgroundExecutor.java:212)
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                      at java.lang.Thread.run(Thread.java:818)`

**Comment by kevalpatel2106** [comment]
Can you specify your device model and android version you have?

**Comment by Sateesh2** [comment]
Hi, I was using OnePlus 2 and file size was more than 150 mb. Later I took
your code and replaced mp4parser with ffmpeg and it worked fine.

On Sep 6, 2016 3:10 PM, "Keval Patel" notifications@github.com wrote:

Can you specify your device model and android version you have?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/knowledge4life/k4l-video-trimmer/issues/7#issuecomment-244900931,
or mute the thread

**Comment by dogo** [comment]
@Sateesh2 could you please propose a PR with those changes? they are really interesting

**Comment by Sateesh2** [comment]
@dogo I just created PR with above-mentioned changes. Sorry for the late reply

**Comment by ashishvirani29** [comment]
i have same issue please give solution.

**Comment by Sateesh2** [comment]
Hi, Ashish, the reason for the out of memory issue is the latest mp4parser changes. So I took the current project and rolled back mp4parser to "com.googlecode.mp4parser:isoparser:1.1.7". You may need to update one or two lines in TrimVideoUtils class. Let me know if you are stuck.

**Comment by kushmpatel** [comment]
@Sateesh2 Hi I am facing the same problem. So can you please give me a code? I have changed my dependency from "com.googlecode.mp4parser:isoparser:1.1.20" to "com.googlecode.mp4parser:isoparser:1.1.7".

**Comment by Sateesh2** [comment]
In TrimVideoUtils.java file go to genVideoUsingMp4Parser() method, in the first line of this method change FileDataSourceViaHeapImpl to FileDataSourceImpl.

**Comment by anuj7sharma** [comment]
Changing FileDataSourceViaHeapImpl to FileDataSourceImpl is not helping. Crash issue still persists.
